version: '3.4'

networks:
  k6:

services:

  k6:
    image: loadimpact/k6:latest
    networks:
      - k6
    ports:
      - "6560-6570"
    command: "run /scripts/script.js --vus 100 --duration 10s --no-usage-report --rps 30"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./samples:/scripts